### ISSUE TITLE
The mode of decoding

### ISSUE THREAD

**Issue by AMKaffiOS** [Anakros/webrtc-ios-dynamic#31]
What is the default mode of decoding，How do I choose hardware decoding or software decoding?
thanks！

**Comment by AlexKMDev** [comment]
It's software decoding by default (VP8 codec). In order to use hardware decoding with H264 you need to replace the order of codec priority in SDP. The appropriate code to do it can be found [here](https://github.com/WebKit/webkit/blob/master/Source/ThirdParty/libwebrtc/Source/webrtc/examples/objc/AppRTCMobile/ARDSDPUtils.m).

Then just call it with needed argument:
```swift
let description = ARDSDPUtils.description(for: offerDescription, preferredVideoCodec: "H264")
```
And "VP8" if you need software decoding back.
